### ISSUE TITLE
1.12.2 regex

### ISSUE THREAD

**Issue by cajlo** [baka-gourd/LogUnSpam#6] opened 2023-10-30 22:21 UTC
I don't understand how to use regex with it. tried with just a regex line, tried with "", with (), with \ \g, it simply doesnt make any effort.

I've downloaded all 5 modpacks that use this mod, none of them use regex.

I've checked my regex on https://www.freeformatter.com/java-regex-tester.html#before-output and on others.
String "Found[\S ]+This is not recommended, @Mods should be in a separate jar from the coremod\." have 3 matches in text like:

    "[00:16:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in aaa_SmoothEntityLight-4.0.4-MC1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
    [00:16:23] [main/WARN] [FML]: The coremod SmoothEntityLight (lakmoore.sel.common.FMLCorePlugin) is not signed!
    [00:16:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in aab_configanytime-1.0--OPTICRAFT_Valkyrie+UniversalTweaks.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
    [00:16:23] [main/WARN] [FML]: The coremod com.cleanroommc.configanytime.ConfigAnytimePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
    [00:16:23] [main/WARN] [FML]: The coremod ConfigAnytimePlugin (com.cleanroommc.configanytime.ConfigAnytimePlugin) is not signed!
    [00:16:23] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from aab_mixin_MixinCompat-1.1-1.12.2_.jar
    [00:16:23] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in aab_Red-Core-0.4--OPTICRAFT_Alfheim+Valkyrie.jar. This is not recommended, @Mods should be in a separate jar from the coremod."

but not in minecraft. I don't know why =\

**Comment by cajlo** [comment] 2023-10-30 22:49
I felt myself a little bit stupid, because I forgot to check, if mod is already working, but it is not working

    
    [01:45:35] [Client thread/INFO] [log_un_spam]: LogUnSpam loaded.
    [01:45:35] [Client thread/INFO] [log_un_spam]: Applying filters...
    [01:45:35] [Client thread/INFO] [log_un_spam]: Filter has 0 common rule(s), 4 regex rule(s) and 0 Fqcn rule(s).
    [01:45:35] [Client thread/INFO] [log_un_spam]: Filters applied.
    
    
    [01:45:35] [Client thread/INFO] [Quark]: 'Tiny potato' is forcefully disabled as it's incompatible with the following loaded mods: [botania]
    [01:45:35] [Client thread/INFO] [Quark]: Module vanity is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module client is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module world is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module building is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module decoration is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module automation is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module misc is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module tweaks is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module management is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module oddities is enabled
    [01:45:35] [Client thread/INFO] [Quark]: Module experimental is disabled


And my regex is


        # Regular expressions that will be filtered out.
        S:RegExpFilterWords <
            Found[\S ]+This is not recommended, @Mods should be in a separate jar from the coremod\.
            "\[Quark\][\S ]+abled"
            (\[Quark\][\S ]+abled)
            \[Quark\][\S ]+abled
         >

**Comment by baka-gourd** [comment] 2023-10-31 01:16
You're actually using it in the right way, but the problem is almost insurmountable. The reason is simple, quark may outputs the log before logunspam loaded. Forge is now multi-threaded when loading mods, and the order is not controllable. I can't guarantee that my mod will be loaded first in the same stage, and there's nothing that can be done about it.
But for your log, you can try use `Module .+ is (dis|en)abled` to filter quark log.
As disappointing as this sounds, this mod can't filter log form coremod because this mod comes after coremod loaded.

**Comment by GBLodb** [comment] 2023-11-03 11:18
Closed as legacy, reopen if needed.

**Closed as completed by GBLodb** 2023-11-03 11:18 UTC
